spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: my-spring-app                 # Matches the clientId in Keycloak
            client-secret: myCustomSecret123!        # Matches the client secret in Keycloak
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/my-app-realm   # Your Keycloak realm's issuer URI
            user-info-uri: http://localhost:8081/realms/my-app-realm/protocol/openid-connect/userinfo
