version: '3'
services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"                   # Cassandra CQL native transport port
    environment:
      CASSANDRA_CLUSTER_NAME: "Test Cluster"
      CASSANDRA_NUM_TOKENS: 16
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 100M
    networks:
      - cassandra_network

networks:
  cassandra_network:
    driver: bridge
